### ISSUE TITLE
Get client handle.vi doesn't remove old headers.

### ISSUE THREAD

**Issue by MichaelAivaliotis** [JKISoftware/JKI-HTTP-REST-Client#3] opened 2017-09-06 03:21 UTC
I noticed that inside this VI, the comment states that the old headers are being removed. However, the AddHeader.vi is used. Wondering if this is a bug, or I'm not understanding something.

![2017-09-05_20-15-39](https://user-images.githubusercontent.com/7982554/30093010-5c77d446-9277-11e7-9788-551465283b9c.png)

**Comment by jimkring** [comment] 2017-09-06 03:29
Hi Michael,

It appears to be writing an empty string to the header items, which might
have a similar effect as removing them.

It would seem more robust to use Remove Header instead:
http://zone.ni.com/reference/en-XX/help/371361L-01/lvcomm/http_client_removeheader/

I'm not sure the reasoning for the existing implementation or if it's an
oversight. It's worth investigating.

**Comment by tmaila** [comment] 2017-09-06 04:47
This pattern is not a bug and was purely introduced to address a limitation of the earlier versions of LabVIEW HTTP client. This pattern allowed to delete old headers and replace them with new ones. There was no delete header VI but the same functionality was achieved by writing an empty header.

**Comment by jimkring** [comment] 2019-02-18 19:01
question answered, so I'll close this issue

**Closed by jimkring** 2019-02-18 19:01 UTC
Labels: question
