### ISSUE TITLE
HTTP DELETE.vi is broken

### ISSUE THREAD

**Issue by KShireyNTG** [JKISoftware/JKI-HTTP-REST-Client#16] opened 2020-05-14 22:29 UTC
Found an error in the Restful API for LabVIEW 2017 32bit during a build. I had to add it to my project directly (llb) and override removing of the block diagram. 

A VI broke during the build process from being saved without a block diagram. Either open the build specification to include the block diagram of that VI or enable debugging to include the block diagrams of all VIs in the build. Report this error to National Instruments technical support.
C:\Program Files (x86)\National Instruments\LabVIEW 2017\vi.lib\addons\_JKI.lib\REST Client\classes\REST Client\HTTP DELETE.vi

**Comment by jimkring** [comment] 2020-05-15 20:24
Hi Kevin,

Would you be able to create a super small example project with a build specification that reproduces the issue, zip it up, and post it here? That would be a big help in reproducing and fixing it.

Thanks!

-Jim

**Comment by KShireyNTG** [comment] 2020-05-19 18:28
[JIRA Reporter Public.zip](https://github.com/JKISoftware/JKI-HTTP-REST-Client/files/4652433/JIRA.Reporter.Public.zip)
This is the LabVIEW 2017 project. I hope you can find the same issue and resolve. thanks!

**Comment by jimkring** [comment] 2020-05-19 19:26
Hi Kevin. I think the issue is that "HTTP DELETE.vi" is broken because an important required input is missing from a subVI.  I'll look into fixing this in the official package/release. Until then, here's a workaround -- just wire it up:

![image](https://user-images.githubusercontent.com/381432/82369403-d0e06880-99cb-11ea-86f5-fe6c666810f7.png)

Please let me know if that works for you.

**Comment by KShireyNTG** [comment] 2020-05-19 19:35
Thanks Jim, that did the trick. I'll look for the next update on VIPM for our developers for the next project coming up.

**Comment by jimkring** [comment] 2020-05-19 19:56
This is a duplicate of #13

**Comment by jimkring** [comment] 2020-05-19 20:38
The fix is now available in VIPM and GitHub releases:
https://www.vipm.io/package/jki_lib_rest_client/
https://github.com/JKISoftware/JKI-HTTP-REST-Client/releases/

**Closed by jimkring** 2020-05-19 20:38 UTC
Labels: duplicate
